### ISSUE TITLE
Load sb2 project into 3.0 project view

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-www#1799]
A user can load an existing sb2 project. They get a preliminary (pre-design) project view including metadata from the sb2 project (title, instructions, etc)

- [x] Title
- [x] Author:
  - [x] Avatar
  - [x] username as link to profile
- [x] share date with 'copyleft' symbol
- [x] remix credit if project is a remix
- [x] description (combination of current description and instructions fields - will need migration)
  - [x] `@mentions` and `#hashtags` should be linked in description
- [x] stats
  - [x] loves - number of loves, logged in user can toggle loved status
  - [x] favorites - number of favorites, logged in user can toggle fav status
  - [x] remixes - numer of remixes
  - [x] views - number of views capped at 100
- [x] list of remixes
- [x] list of studios
- [x] player - gui placeholder

Buttons:
- [ ] ~~share banner with share button if project unshared~~ see #1873
- [x] Remix button if logged in user and not the author
- [ ] ~~See inside (opens GUI)~~ see #1874
- [ ] ~~Add to studio~~ see #1872
- [ ] ~~Report~~ see #1857  
- [ ] ~~Social~~ see #1852 

Excludes comments.
