### ISSUE TITLE
Project page responsiveness - Phase 1

### ISSUE THREAD

**Issue by benjiwheeler** [LLK/scratch-www#2310]
See https://github.com/LLK/scratch-www/issues/2115 for overall designs.

Phase 1 of Project page responsiveness work:

- [ ] Adjust overall breakpoints https://github.com/LLK/scratch-www/issues/2113
- [ ] Sign in button should show on mobile https://github.com/LLK/scratch-www/issues/2243
- [ ] Main items should stack below/at 768
- [ ] Nothing should look super weird on the Project page!
- [ ] Remix, see inside hidden below/at 768 https://github.com/LLK/scratch-www/issues/2268
- [ ] "Explore more" is dropped < 960 https://github.com/LLK/scratch-www/issues/2268
- [ ] Make title/instructions non editable at/below 480 https://github.com/LLK/scratch-www/issues/2268
- [ ] Read only comments on mobile https://github.com/LLK/scratch-www/issues/2268
  - [ ] Appearance https://github.com/LLK/scratch-www/issues/2140
  - [ ] hide post box completely
  - [ ] Hide reply

**Comment by kyleplo** [comment]
Why should comments be read-only on mobile?

**Comment by benjiwheeler** [comment]
Tracking in https://github.com/LLK/scratch-www/projects/1
