### ISSUE TITLE
Project page responsiveness - Phase 2

### ISSUE THREAD

**Issue by benjiwheeler** [LLK/scratch-www#2311]
See https://github.com/LLK/scratch-www/issues/2115 for overall designs.

Phase 2 of Project page responsiveness work:

- [ ] Rotating into landscape makes player go fullscreen https://github.com/LLK/scratch-gui/issues/3414
- [ ] Landscape on an iPhone X
- [ ] Menu items 
  - [ ] Messages should stay right aligned
- [ ] Landscape orientation issue https://github.com/LLK/scratch-gui/issues/3229
  * Will take some iterations
  * Several interlocking questions
  * Try to do it before jan, to get feedback from community and maybe a recess of us?
- [ ] Make editable instructions text areas not too tall, with padding on sides so whole page is still scrollable
- [ ] Resolve css issues with share banner PR: https://github.com/LLK/scratch-www/pull/2148
- [ ] Player size should transition more naturally https://github.com/LLK/scratch-www/issues/2084

**Comment by towerofnix** [comment]
(This should also be labelled "responsiveness"!)

**Comment by benjiwheeler** [comment]
Tracking in https://github.com/LLK/scratch-www/projects/1
