### ISSUE TITLE
Project page responsiveness - Phase 3

### ISSUE THREAD

**Issue by benjiwheeler** [LLK/scratch-www#2312]
See Phase 1: https://github.com/LLK/scratch-www/issues/2310 , Phase 2: https://github.com/LLK/scratch-www/issues/2311

- [ ] Investigate minimum editor dimensions https://github.com/LLK/scratch-gui/issues/3708
- [ ] Make sure player fits with project page responsiveness https://github.com/LLK/scratch-gui/issues/3196
- [ ] Mobile footer responsiveness https://github.com/LLK/scratch-www/issues/892
- [ ] Footer: https://github.com/LLK/scratch-www/issues/2321
- [ ] Extensions page: https://github.com/LLK/scratch-www/issues/2320
- [ ] Modal responsiveness https://github.com/LLK/scratch-www/issues/1969 https://github.com/LLK/scratch-www/issues/2159
- [ ] Love/fave responsiveness https://github.com/LLK/scratch-www/issues/2246

**Comment by benjiwheeler** [comment]
Tracking in https://github.com/LLK/scratch-www/projects/1
