### ISSUE TITLE
Update Tips to Ideas page

### ISSUE THREAD

**Issue by carljbowman** [LLK/scratch-www#2362]
### Overview
When we launch Scratch 3.0 we will need to update the Tips page. All the current content for 2.0 will not longer be relevant. At a high-level this update will include replacing 2.0 content with 3.0 content, some UX changes, and reframing the page as "Ideas."

### ToDo
- [x] Get remaining 3 tutorials and assets up to GUI (KO & Eric)
  - [x] KO to handoff JSON and assets to Eric for the following tutorials (KO)
    - [x] Animate a Character
    - [x] Make a Catch Game
    - [x] Video Sensing
  - [x] Eric to create a PR and merge (Eric)
- [x] Create new URL “/ideas” (Eric)
- [x] Create redirect for “/tips” and “/go” to “/ideas” (Eric)
- [x] Change text/URL in navbar and footer from “Tips” to “Ideas” (Eric)
  - [x]  On www
  - [x]  On scratchr2
- [x] Update “Tips page” language on Educators page (Eric)
- [x] Implement new layout “Ideas” page (Eric)
- [x] Finish masthead illustration and share with Eric (Carl)
- [x] Finish starter projects illustration and share with Eric (Carl)
- [x] Create and share Tutorial modal images with Eric (KO)
- [x] Share Tutorial tile images with Eric (KO)
- [x] Upload Activity Card PDFs and Educator Guides PDFs to AWS and share with Eric (Natalie)

#### Page
![v3 ideas page](https://user-images.githubusercontent.com/3409578/49652119-21921a80-f9ff-11e8-930d-f1c69282e8cd.png)

#### Activity Modal
![v3_ideas page modal](https://user-images.githubusercontent.com/3409578/49311076-17779580-f4ae-11e8-9565-d8d3e16daa76.png)

### Content

**Copy** — [Google Doc](https://docs.google.com/document/d/1k_Xkbi0Blt-8oN17QzvB0xlTe7VfjWL_6a_V9pY02JU/edit)

**Illustrations & Icons** — [ideas-page-assets-v3.zip](https://github.com/LLK/scratch-www/files/2663772/ideas-page-assets-v3.zip)

**Tutorial Tile Images** — @kosiecki17 to provide

**Tutorial Modal Images** — @kosiecki17 to provide

**Comment by ntlrsk** [comment]
@ericrosenbaum @carljbowman  Note: wording change: Activity Cards --> Coding Cards

**Comment by carljbowman** [comment]
@ntlrsk - Updated the mocks to match the new language.

**Comment by ntlrsk** [comment]
Those are good suggestions for dynamic content on the ideas page, @kyleplo

**Comment by carljbowman** [comment]
Updated the assets zip and mock to include new illustrations.

**Comment by yusuf989** [comment]
The about page link to the ideas page still reads "Tips Page" (under "Learn More About Scratch" section near the bottom of the page.

**Comment by towerofnix** [comment]
@yusuf989 you should [create a new issue](https://github.com/LLK/scratch-www/issues/new) for that, so it can be properly tracked and fixed as its own new issue.
