### ISSUE TITLE
Teacher Account Join Flow

### ISSUE THREAD

**Issue by kaschm** [LLK/scratch-www#409]
Need:

- [x] Final Copy https://docs.google.com/spreadsheets/d/1IlqxvbaKPqCbRZaUOqWPO0LyDbaqBqQuJDDCq5kwLqg/edit (ping me if you need access) 
- [x] Final Designs (@carljbowman)

**Comment by carljbowman** [comment]
@rschamp - Posting the most recent version of the Teacher Join Flow wireframes:
[**R1.4_Teacher Join Flow.pdf**](https://github.com/LLK/scratch-www/files/241025/R1.4_Teacher.Join.Flow.pdf)

Major changes include:
- Adding a Captcha form step (tech TBD)
- Updated 'Password' form on the account creation form step (page 5) to include a visibility toggle; language and UI will be defined in final designs. This update is also reflected in the Student Join Flows which can be found here: https://github.com/LLK/scratchr2/issues/353 . Going forward this will be a become a standard across all Join Flows.

#### Teacher Join Flow Overview
![r1 4_teacher-join-flow](https://cloud.githubusercontent.com/assets/3409578/14894454/b88903de-0d41-11e6-964d-59659b7cda3e.png)

Please let me know if you addtional questions or comments. Moving to final designs with final content.

**Comment by carljbowman** [comment]
# Design Pass
Illustrator File: [R3.1_Teacher Join Flow.ai.zip](https://github.com/LLK/scratch-www/files/296200/R3.1_Teacher.Join.Flow.ai.zip)


**Todo**
- [ ] Content for Step 9 - Captcha ( @kaschm )
- [ ] Content for Step 10 - Application Review - 'Check out Resources' section. Pointing Teachers to For Educator page and to Teacher Account FAQ. ( @kaschm )
- [ ] Icons for Step 10 - Application Review ( @carljbowman )

## Step 1 - Username & Password
#### Input - Focus
![r3 1_teacher-join-flow step1-typing](https://cloud.githubusercontent.com/assets/3409578/15749332/fac87d04-28af-11e6-9f8a-f1b01e6e73ef.png)

#### Check box - Showing password
![r3 1_teacher-join-flow step1](https://cloud.githubusercontent.com/assets/3409578/15747805/6be36694-28aa-11e6-8f56-c636b6a71ed6.png)

#### Tooltip - Error (Desktop)
![r3 1_teacher-join-flow step1-error-tooltip](https://cloud.githubusercontent.com/assets/3409578/15754656/36289b6a-28c7-11e6-894c-51b0e2b175d8.png)

#### Tooltip - Error (Mobile) 
![r3 1_teacher-join-flow step1-error-tooltip-mobile](https://cloud.githubusercontent.com/assets/3409578/15751492/4f8fe1a8-28b8-11e6-91a2-0a8f7802557f.png)


## Step 2 - Personal Information
![r3 1_teacher-join-flow step2](https://cloud.githubusercontent.com/assets/3409578/15747829/7d0aad1a-28aa-11e6-88ea-0ed1413677e0.png)

#### Dropdown - Open
![r3 1_teacher-join-flow step2-dropdown](https://cloud.githubusercontent.com/assets/3409578/15753701/706cd6f6-28c2-11e6-9a9b-2db60ed20515.png)


## Step 3 -  First & Last Name
![r3 1_teacher-join-flow step3](https://cloud.githubusercontent.com/assets/3409578/15747909/d2f44f60-28aa-11e6-8503-673517b22a05.png)

#### Tooltip - Info Hover
![r3 1_teacher-join-flow step3-info-tooltip](https://cloud.githubusercontent.com/assets/3409578/15754702/81c7c708-28c7-11e6-8dc2-3c737c492a56.png)


## Step 4 - Phone Number
![r3 1_teacher-join-flow step4](https://cloud.githubusercontent.com/assets/3409578/15747859/a17ca7d4-28aa-11e6-9cc8-2692e51b6d61.png)

## Step 5 - Organization
![r3 1_teacher-join-flow step5](https://cloud.githubusercontent.com/assets/3409578/15747925/e3e24c64-28aa-11e6-86b6-e55139d703f2.png)

## Step 6 - Address
![r3 1_teacher-join-flow step6](https://cloud.githubusercontent.com/assets/3409578/15747934/ec129510-28aa-11e6-9538-e2247bd98238.png)

## Step 7 - How I plan to use Scratch?
 ![r3 1_teacher-join-flow step7](https://cloud.githubusercontent.com/assets/3409578/15747954/f825bd00-28aa-11e6-931e-72eafce99457.png)

## Step 8 - Email Address
![r3 1_teacher-join-flow step8](https://cloud.githubusercontent.com/assets/3409578/15747960/00889422-28ab-11e6-814b-1cdfc4722ab9.png)

## Step 9 - Captcha
![r3 1_teacher-join-flow step9](https://cloud.githubusercontent.com/assets/3409578/15747981/0dc3208a-28ab-11e6-8c4f-80d761cfaac5.png)

## Step 10 - Application Review
![r3 1_teacher-join-flow final](https://cloud.githubusercontent.com/assets/3409578/15748003/1efbe224-28ab-11e6-8572-b19e4238218a.png)

**Comment by rschamp** [comment]
Offline @thisandagain and I decided to forego the captcha for a hidden field, so we don't need content for that card, that step will not exist.

**Comment by kaschm** [comment]
Text on Step 10:

**Get Started with Resources**
Explore materials for educators and facilitators written by the Scratch Team, including [tips, tutorials, and teaching curricula](scratch.mit.edu/educators#resources). 

[link should be anchor link to the resources part of the educators page]

**Comment by rschamp** [comment]
@carljbowman @kaschm Please confirm regarding the waiting period behavior:
* Before the teacher status is activated: My Classes links to Step 10 - Application Review
* After the teacher status is activated: My Classes should pop up the "confirm email" dialog
